# Generated by Django 5.2.5 on 2025-08-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
