# Generated by Django 5.2.5 on 2025-08-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0003_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
